-- Superseded by credit_report_setup.sql — run that one instead.
--
-- This file used to create the credit tables and then drop the three tables the
-- very first version of the page used. Those drops are the problem: a drop that
-- trips over a dependency fails the whole script, so the tables above it never
-- got created and the Credit Report page sat empty with no explanation.
--
-- credit_report_setup.sql does everything this did, only creating and adding,
-- and is safe to run over and over.
--
-- If the first version's tables are still lying around, they're harmless — the
-- app never reads them. To clear them out, run these one at a time so a failure
-- on one doesn't stop the others:
--
--   drop table if exists public.credit_report_accounts;
--   drop table if exists public.fico_scores;
--   drop table if exists public.credit_reports;
